#
# Dockerfile to build adtools GCC 4 cross-compiler
#
# The binaries will ultimately be found in /opt/adtools
#
# The idea with this image is to produce a bare minimum base from
# which to create more specific builders. The cross-compiler
# executes but no other tools are available.
#

FROM debian:buster

LABEL maintainer="Steven Solie <steven@solie.ca>"

#
# This is where the build will take place and is removed when finished.
#
WORKDIR /work

#
# Perform all the steps in a single RUN to avoid creating file system layers.
#
RUN apt-get update && apt-get upgrade --yes && \
  apt-get install -y \
    git \
    python2.7 \
    make \
    libgmp-dev \
    libmpc-dev \
    libtool \
    flex \
    bison \
    texinfo \
    wget \
    lhasa \
  && \
  mv /etc/apt/sources.list /etc/apt/sources.list.bak && \
  echo "deb http://ftp.us.debian.org/debian/ jessie main contrib non-free" > /etc/apt/sources.list && \
  echo "deb-src http://ftp.us.debian.org/debian/ jessie main contrib non-free" >> /etc/apt/sources.list && \
  apt-get update && \
  apt-get install -y g++-4.9 && \
  mv /etc/apt/sources.list.bak /etc/apt/sources.list \
  && \
  ln -s /usr/bin/python2.7 /usr/bin/python && \
  ln -s /usr/bin/g++-4.9 /usr/bin/g++ && \
  rm /usr/bin/gcc && \
  ln -s /usr/bin/gcc-4.9 /usr/bin/gcc \
  && \
  git config --global user.email me@github.com && \
  git clone https://github.com/sba1/adtools . && \
  git submodule init && \
  git submodule update && \
  echo -e "4.9\treleases/gcc-4.9.3\thttp://ftp.gnu.org/gnu/gcc/gcc-4.9.3/gcc-4.9.3.tar.bz2" > gcc/series && \
  gild/bin/gild clone && \
  gild/bin/gild checkout binutils 2.23.2 && \
  gild/bin/gild checkout gcc 4.9 \
  && \
  make -C native-build gcc-cross CROSS_PREFIX=/opt/adtools \
  && \
  rm -rf /work/* && \
  rm /usr/bin/python && \
  rm /usr/bin/gcc && \
  rm /usr/bin/g++ \
  && \
  apt-get --assume-yes purge \
    git \
    python2.7 \
    make \
    libgmp-dev \
    libmpc-dev \
    libtool \
    flex \
    bison \
    texinfo \
    wget \
    lhasa \
    g++-4.9 \
  && \
  apt-get --assume-yes autoremove && \
  apt-get clean && \
  rm -rf /var/lib/apt/lists/*
